// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i net-playground/internal/services/dummy.repo -o repo_mock.go -n RepoMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"net-playground/internal/domain/dto"

	"github.com/gojuno/minimock/v3"
)

// RepoMock implements mm_dummy.repo
type RepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcGetInfos          func(ctx context.Context) (gpa1 []*dto.GetDummyInfo, err error)
	funcGetInfosOrigin    string
	inspectFuncGetInfos   func(ctx context.Context)
	afterGetInfosCounter  uint64
	beforeGetInfosCounter uint64
	GetInfosMock          mRepoMockGetInfos

	funcSave          func(ctx context.Context, data string) (err error)
	funcSaveOrigin    string
	inspectFuncSave   func(ctx context.Context, data string)
	afterSaveCounter  uint64
	beforeSaveCounter uint64
	SaveMock          mRepoMockSave
}

// NewRepoMock returns a mock for mm_dummy.repo
func NewRepoMock(t minimock.Tester) *RepoMock {
	m := &RepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetInfosMock = mRepoMockGetInfos{mock: m}
	m.GetInfosMock.callArgs = []*RepoMockGetInfosParams{}

	m.SaveMock = mRepoMockSave{mock: m}
	m.SaveMock.callArgs = []*RepoMockSaveParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mRepoMockGetInfos struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockGetInfosExpectation
	expectations       []*RepoMockGetInfosExpectation

	callArgs []*RepoMockGetInfosParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockGetInfosExpectation specifies expectation struct of the repo.GetInfos
type RepoMockGetInfosExpectation struct {
	mock               *RepoMock
	params             *RepoMockGetInfosParams
	paramPtrs          *RepoMockGetInfosParamPtrs
	expectationOrigins RepoMockGetInfosExpectationOrigins
	results            *RepoMockGetInfosResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockGetInfosParams contains parameters of the repo.GetInfos
type RepoMockGetInfosParams struct {
	ctx context.Context
}

// RepoMockGetInfosParamPtrs contains pointers to parameters of the repo.GetInfos
type RepoMockGetInfosParamPtrs struct {
	ctx *context.Context
}

// RepoMockGetInfosResults contains results of the repo.GetInfos
type RepoMockGetInfosResults struct {
	gpa1 []*dto.GetDummyInfo
	err  error
}

// RepoMockGetInfosOrigins contains origins of expectations of the repo.GetInfos
type RepoMockGetInfosExpectationOrigins struct {
	origin    string
	originCtx string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetInfos *mRepoMockGetInfos) Optional() *mRepoMockGetInfos {
	mmGetInfos.optional = true
	return mmGetInfos
}

// Expect sets up expected params for repo.GetInfos
func (mmGetInfos *mRepoMockGetInfos) Expect(ctx context.Context) *mRepoMockGetInfos {
	if mmGetInfos.mock.funcGetInfos != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by Set")
	}

	if mmGetInfos.defaultExpectation == nil {
		mmGetInfos.defaultExpectation = &RepoMockGetInfosExpectation{}
	}

	if mmGetInfos.defaultExpectation.paramPtrs != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by ExpectParams functions")
	}

	mmGetInfos.defaultExpectation.params = &RepoMockGetInfosParams{ctx}
	mmGetInfos.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetInfos.expectations {
		if minimock.Equal(e.params, mmGetInfos.defaultExpectation.params) {
			mmGetInfos.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetInfos.defaultExpectation.params)
		}
	}

	return mmGetInfos
}

// ExpectCtxParam1 sets up expected param ctx for repo.GetInfos
func (mmGetInfos *mRepoMockGetInfos) ExpectCtxParam1(ctx context.Context) *mRepoMockGetInfos {
	if mmGetInfos.mock.funcGetInfos != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by Set")
	}

	if mmGetInfos.defaultExpectation == nil {
		mmGetInfos.defaultExpectation = &RepoMockGetInfosExpectation{}
	}

	if mmGetInfos.defaultExpectation.params != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by Expect")
	}

	if mmGetInfos.defaultExpectation.paramPtrs == nil {
		mmGetInfos.defaultExpectation.paramPtrs = &RepoMockGetInfosParamPtrs{}
	}
	mmGetInfos.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetInfos.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetInfos
}

// Inspect accepts an inspector function that has same arguments as the repo.GetInfos
func (mmGetInfos *mRepoMockGetInfos) Inspect(f func(ctx context.Context)) *mRepoMockGetInfos {
	if mmGetInfos.mock.inspectFuncGetInfos != nil {
		mmGetInfos.mock.t.Fatalf("Inspect function is already set for RepoMock.GetInfos")
	}

	mmGetInfos.mock.inspectFuncGetInfos = f

	return mmGetInfos
}

// Return sets up results that will be returned by repo.GetInfos
func (mmGetInfos *mRepoMockGetInfos) Return(gpa1 []*dto.GetDummyInfo, err error) *RepoMock {
	if mmGetInfos.mock.funcGetInfos != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by Set")
	}

	if mmGetInfos.defaultExpectation == nil {
		mmGetInfos.defaultExpectation = &RepoMockGetInfosExpectation{mock: mmGetInfos.mock}
	}
	mmGetInfos.defaultExpectation.results = &RepoMockGetInfosResults{gpa1, err}
	mmGetInfos.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetInfos.mock
}

// Set uses given function f to mock the repo.GetInfos method
func (mmGetInfos *mRepoMockGetInfos) Set(f func(ctx context.Context) (gpa1 []*dto.GetDummyInfo, err error)) *RepoMock {
	if mmGetInfos.defaultExpectation != nil {
		mmGetInfos.mock.t.Fatalf("Default expectation is already set for the repo.GetInfos method")
	}

	if len(mmGetInfos.expectations) > 0 {
		mmGetInfos.mock.t.Fatalf("Some expectations are already set for the repo.GetInfos method")
	}

	mmGetInfos.mock.funcGetInfos = f
	mmGetInfos.mock.funcGetInfosOrigin = minimock.CallerInfo(1)
	return mmGetInfos.mock
}

// When sets expectation for the repo.GetInfos which will trigger the result defined by the following
// Then helper
func (mmGetInfos *mRepoMockGetInfos) When(ctx context.Context) *RepoMockGetInfosExpectation {
	if mmGetInfos.mock.funcGetInfos != nil {
		mmGetInfos.mock.t.Fatalf("RepoMock.GetInfos mock is already set by Set")
	}

	expectation := &RepoMockGetInfosExpectation{
		mock:               mmGetInfos.mock,
		params:             &RepoMockGetInfosParams{ctx},
		expectationOrigins: RepoMockGetInfosExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetInfos.expectations = append(mmGetInfos.expectations, expectation)
	return expectation
}

// Then sets up repo.GetInfos return parameters for the expectation previously defined by the When method
func (e *RepoMockGetInfosExpectation) Then(gpa1 []*dto.GetDummyInfo, err error) *RepoMock {
	e.results = &RepoMockGetInfosResults{gpa1, err}
	return e.mock
}

// Times sets number of times repo.GetInfos should be invoked
func (mmGetInfos *mRepoMockGetInfos) Times(n uint64) *mRepoMockGetInfos {
	if n == 0 {
		mmGetInfos.mock.t.Fatalf("Times of RepoMock.GetInfos mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetInfos.expectedInvocations, n)
	mmGetInfos.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetInfos
}

func (mmGetInfos *mRepoMockGetInfos) invocationsDone() bool {
	if len(mmGetInfos.expectations) == 0 && mmGetInfos.defaultExpectation == nil && mmGetInfos.mock.funcGetInfos == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetInfos.mock.afterGetInfosCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetInfos.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetInfos implements mm_dummy.repo
func (mmGetInfos *RepoMock) GetInfos(ctx context.Context) (gpa1 []*dto.GetDummyInfo, err error) {
	mm_atomic.AddUint64(&mmGetInfos.beforeGetInfosCounter, 1)
	defer mm_atomic.AddUint64(&mmGetInfos.afterGetInfosCounter, 1)

	mmGetInfos.t.Helper()

	if mmGetInfos.inspectFuncGetInfos != nil {
		mmGetInfos.inspectFuncGetInfos(ctx)
	}

	mm_params := RepoMockGetInfosParams{ctx}

	// Record call args
	mmGetInfos.GetInfosMock.mutex.Lock()
	mmGetInfos.GetInfosMock.callArgs = append(mmGetInfos.GetInfosMock.callArgs, &mm_params)
	mmGetInfos.GetInfosMock.mutex.Unlock()

	for _, e := range mmGetInfos.GetInfosMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gpa1, e.results.err
		}
	}

	if mmGetInfos.GetInfosMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetInfos.GetInfosMock.defaultExpectation.Counter, 1)
		mm_want := mmGetInfos.GetInfosMock.defaultExpectation.params
		mm_want_ptrs := mmGetInfos.GetInfosMock.defaultExpectation.paramPtrs

		mm_got := RepoMockGetInfosParams{ctx}

		if mm_want_ptrs != nil {
			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetInfos.t.Errorf("RepoMock.GetInfos got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetInfos.GetInfosMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}
		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetInfos.t.Errorf("RepoMock.GetInfos got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetInfos.GetInfosMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetInfos.GetInfosMock.defaultExpectation.results
		if mm_results == nil {
			mmGetInfos.t.Fatal("No results are set for the RepoMock.GetInfos")
		}
		return (*mm_results).gpa1, (*mm_results).err
	}
	if mmGetInfos.funcGetInfos != nil {
		return mmGetInfos.funcGetInfos(ctx)
	}
	mmGetInfos.t.Fatalf("Unexpected call to RepoMock.GetInfos. %v", ctx)
	return
}

// GetInfosAfterCounter returns a count of finished RepoMock.GetInfos invocations
func (mmGetInfos *RepoMock) GetInfosAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInfos.afterGetInfosCounter)
}

// GetInfosBeforeCounter returns a count of RepoMock.GetInfos invocations
func (mmGetInfos *RepoMock) GetInfosBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetInfos.beforeGetInfosCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.GetInfos.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetInfos *mRepoMockGetInfos) Calls() []*RepoMockGetInfosParams {
	mmGetInfos.mutex.RLock()

	argCopy := make([]*RepoMockGetInfosParams, len(mmGetInfos.callArgs))
	copy(argCopy, mmGetInfos.callArgs)

	mmGetInfos.mutex.RUnlock()

	return argCopy
}

// MinimockGetInfosDone returns true if the count of the GetInfos invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetInfosDone() bool {
	if m.GetInfosMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetInfosMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetInfosMock.invocationsDone()
}

// MinimockGetInfosInspect logs each unmet expectation
func (m *RepoMock) MinimockGetInfosInspect() {
	for _, e := range m.GetInfosMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.GetInfos at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetInfosCounter := mm_atomic.LoadUint64(&m.afterGetInfosCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetInfosMock.defaultExpectation != nil && afterGetInfosCounter < 1 {
		if m.GetInfosMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.GetInfos at\n%s", m.GetInfosMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.GetInfos at\n%s with params: %#v", m.GetInfosMock.defaultExpectation.expectationOrigins.origin, *m.GetInfosMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetInfos != nil && afterGetInfosCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.GetInfos at\n%s", m.funcGetInfosOrigin)
	}

	if !m.GetInfosMock.invocationsDone() && afterGetInfosCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.GetInfos at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetInfosMock.expectedInvocations), m.GetInfosMock.expectedInvocationsOrigin, afterGetInfosCounter)
	}
}

type mRepoMockSave struct {
	optional           bool
	mock               *RepoMock
	defaultExpectation *RepoMockSaveExpectation
	expectations       []*RepoMockSaveExpectation

	callArgs []*RepoMockSaveParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// RepoMockSaveExpectation specifies expectation struct of the repo.Save
type RepoMockSaveExpectation struct {
	mock               *RepoMock
	params             *RepoMockSaveParams
	paramPtrs          *RepoMockSaveParamPtrs
	expectationOrigins RepoMockSaveExpectationOrigins
	results            *RepoMockSaveResults
	returnOrigin       string
	Counter            uint64
}

// RepoMockSaveParams contains parameters of the repo.Save
type RepoMockSaveParams struct {
	ctx  context.Context
	data string
}

// RepoMockSaveParamPtrs contains pointers to parameters of the repo.Save
type RepoMockSaveParamPtrs struct {
	ctx  *context.Context
	data *string
}

// RepoMockSaveResults contains results of the repo.Save
type RepoMockSaveResults struct {
	err error
}

// RepoMockSaveOrigins contains origins of expectations of the repo.Save
type RepoMockSaveExpectationOrigins struct {
	origin     string
	originCtx  string
	originData string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSave *mRepoMockSave) Optional() *mRepoMockSave {
	mmSave.optional = true
	return mmSave
}

// Expect sets up expected params for repo.Save
func (mmSave *mRepoMockSave) Expect(ctx context.Context, data string) *mRepoMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &RepoMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.paramPtrs != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by ExpectParams functions")
	}

	mmSave.defaultExpectation.params = &RepoMockSaveParams{ctx, data}
	mmSave.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSave.expectations {
		if minimock.Equal(e.params, mmSave.defaultExpectation.params) {
			mmSave.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSave.defaultExpectation.params)
		}
	}

	return mmSave
}

// ExpectCtxParam1 sets up expected param ctx for repo.Save
func (mmSave *mRepoMockSave) ExpectCtxParam1(ctx context.Context) *mRepoMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &RepoMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &RepoMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.ctx = &ctx
	mmSave.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSave
}

// ExpectDataParam2 sets up expected param data for repo.Save
func (mmSave *mRepoMockSave) ExpectDataParam2(data string) *mRepoMockSave {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &RepoMockSaveExpectation{}
	}

	if mmSave.defaultExpectation.params != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Expect")
	}

	if mmSave.defaultExpectation.paramPtrs == nil {
		mmSave.defaultExpectation.paramPtrs = &RepoMockSaveParamPtrs{}
	}
	mmSave.defaultExpectation.paramPtrs.data = &data
	mmSave.defaultExpectation.expectationOrigins.originData = minimock.CallerInfo(1)

	return mmSave
}

// Inspect accepts an inspector function that has same arguments as the repo.Save
func (mmSave *mRepoMockSave) Inspect(f func(ctx context.Context, data string)) *mRepoMockSave {
	if mmSave.mock.inspectFuncSave != nil {
		mmSave.mock.t.Fatalf("Inspect function is already set for RepoMock.Save")
	}

	mmSave.mock.inspectFuncSave = f

	return mmSave
}

// Return sets up results that will be returned by repo.Save
func (mmSave *mRepoMockSave) Return(err error) *RepoMock {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Set")
	}

	if mmSave.defaultExpectation == nil {
		mmSave.defaultExpectation = &RepoMockSaveExpectation{mock: mmSave.mock}
	}
	mmSave.defaultExpectation.results = &RepoMockSaveResults{err}
	mmSave.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// Set uses given function f to mock the repo.Save method
func (mmSave *mRepoMockSave) Set(f func(ctx context.Context, data string) (err error)) *RepoMock {
	if mmSave.defaultExpectation != nil {
		mmSave.mock.t.Fatalf("Default expectation is already set for the repo.Save method")
	}

	if len(mmSave.expectations) > 0 {
		mmSave.mock.t.Fatalf("Some expectations are already set for the repo.Save method")
	}

	mmSave.mock.funcSave = f
	mmSave.mock.funcSaveOrigin = minimock.CallerInfo(1)
	return mmSave.mock
}

// When sets expectation for the repo.Save which will trigger the result defined by the following
// Then helper
func (mmSave *mRepoMockSave) When(ctx context.Context, data string) *RepoMockSaveExpectation {
	if mmSave.mock.funcSave != nil {
		mmSave.mock.t.Fatalf("RepoMock.Save mock is already set by Set")
	}

	expectation := &RepoMockSaveExpectation{
		mock:               mmSave.mock,
		params:             &RepoMockSaveParams{ctx, data},
		expectationOrigins: RepoMockSaveExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSave.expectations = append(mmSave.expectations, expectation)
	return expectation
}

// Then sets up repo.Save return parameters for the expectation previously defined by the When method
func (e *RepoMockSaveExpectation) Then(err error) *RepoMock {
	e.results = &RepoMockSaveResults{err}
	return e.mock
}

// Times sets number of times repo.Save should be invoked
func (mmSave *mRepoMockSave) Times(n uint64) *mRepoMockSave {
	if n == 0 {
		mmSave.mock.t.Fatalf("Times of RepoMock.Save mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSave.expectedInvocations, n)
	mmSave.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSave
}

func (mmSave *mRepoMockSave) invocationsDone() bool {
	if len(mmSave.expectations) == 0 && mmSave.defaultExpectation == nil && mmSave.mock.funcSave == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSave.mock.afterSaveCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSave.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Save implements mm_dummy.repo
func (mmSave *RepoMock) Save(ctx context.Context, data string) (err error) {
	mm_atomic.AddUint64(&mmSave.beforeSaveCounter, 1)
	defer mm_atomic.AddUint64(&mmSave.afterSaveCounter, 1)

	mmSave.t.Helper()

	if mmSave.inspectFuncSave != nil {
		mmSave.inspectFuncSave(ctx, data)
	}

	mm_params := RepoMockSaveParams{ctx, data}

	// Record call args
	mmSave.SaveMock.mutex.Lock()
	mmSave.SaveMock.callArgs = append(mmSave.SaveMock.callArgs, &mm_params)
	mmSave.SaveMock.mutex.Unlock()

	for _, e := range mmSave.SaveMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSave.SaveMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSave.SaveMock.defaultExpectation.Counter, 1)
		mm_want := mmSave.SaveMock.defaultExpectation.params
		mm_want_ptrs := mmSave.SaveMock.defaultExpectation.paramPtrs

		mm_got := RepoMockSaveParams{ctx, data}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSave.t.Errorf("RepoMock.Save got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.data != nil && !minimock.Equal(*mm_want_ptrs.data, mm_got.data) {
				mmSave.t.Errorf("RepoMock.Save got unexpected parameter data, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSave.SaveMock.defaultExpectation.expectationOrigins.originData, *mm_want_ptrs.data, mm_got.data, minimock.Diff(*mm_want_ptrs.data, mm_got.data))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSave.t.Errorf("RepoMock.Save got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSave.SaveMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSave.SaveMock.defaultExpectation.results
		if mm_results == nil {
			mmSave.t.Fatal("No results are set for the RepoMock.Save")
		}
		return (*mm_results).err
	}
	if mmSave.funcSave != nil {
		return mmSave.funcSave(ctx, data)
	}
	mmSave.t.Fatalf("Unexpected call to RepoMock.Save. %v %v", ctx, data)
	return
}

// SaveAfterCounter returns a count of finished RepoMock.Save invocations
func (mmSave *RepoMock) SaveAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.afterSaveCounter)
}

// SaveBeforeCounter returns a count of RepoMock.Save invocations
func (mmSave *RepoMock) SaveBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSave.beforeSaveCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.Save.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSave *mRepoMockSave) Calls() []*RepoMockSaveParams {
	mmSave.mutex.RLock()

	argCopy := make([]*RepoMockSaveParams, len(mmSave.callArgs))
	copy(argCopy, mmSave.callArgs)

	mmSave.mutex.RUnlock()

	return argCopy
}

// MinimockSaveDone returns true if the count of the Save invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockSaveDone() bool {
	if m.SaveMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SaveMock.invocationsDone()
}

// MinimockSaveInspect logs each unmet expectation
func (m *RepoMock) MinimockSaveInspect() {
	for _, e := range m.SaveMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.Save at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSaveCounter := mm_atomic.LoadUint64(&m.afterSaveCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SaveMock.defaultExpectation != nil && afterSaveCounter < 1 {
		if m.SaveMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to RepoMock.Save at\n%s", m.SaveMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to RepoMock.Save at\n%s with params: %#v", m.SaveMock.defaultExpectation.expectationOrigins.origin, *m.SaveMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSave != nil && afterSaveCounter < 1 {
		m.t.Errorf("Expected call to RepoMock.Save at\n%s", m.funcSaveOrigin)
	}

	if !m.SaveMock.invocationsDone() && afterSaveCounter > 0 {
		m.t.Errorf("Expected %d calls to RepoMock.Save at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SaveMock.expectedInvocations), m.SaveMock.expectedInvocationsOrigin, afterSaveCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockGetInfosInspect()

			m.MinimockSaveInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetInfosDone() &&
		m.MinimockSaveDone()
}
